### ISSUE TITLE
How to implement the basic call and speak specific text

### ISSUE THREAD

**Issue by msundiitalk** [team-telnyx/telnyx-python#38]
I have very simple requirement: 

1.  Make a Phone call
2. When client answered the call, play a text : Say this on the call.

Here is the official document link:
[Speak text](https://developers.telnyx.com/docs/api/v2/call-control/Call-Commands#callSpeak)

According to above instructions:
When I use below code to make call and try to speak something:
`
```python

    # outgoing call
    call = telnyx.Call.create(connection_id="uuid", to="+18005550199", from_="+18005550100")
    call.speak(payload="Say this on the call")
````

I got error message:
`telnyx.error.InvalidParametersError: Call not answered yetFull details: [{'code': '90034', 'detail': "This call can't receive speak command because it has not been answered yet.", 'title': 'Call not answered yet'}]
`

Then I think that `call.speak` should implement in `webhook`.
So I added a webhook and implement below code according to above link:
`
```python

    @csrf_exempt
    def telnyx_webhook(request):
        data = json.loads(request.body).get('data')
        if data.get('record_type') == 'event':
            event = data.get('event_type')
            if event == "call.answered":
                print("say something")
                call = telnyx.Call.create()
                call.id = data.get('payload').get('call_control_id')
                call.speak(payload="Say this on the call")
````

But I got the error message since `connection_id ` is required whan call telnyx.Call.create() 
`telnyx.error.InvalidParametersError: Invalid value for connection_idFull details: [{'code': '10015', 'detail': 'The requested connection_id is either invalid or does not exist. Only call control connections with valid webhook URL are accepted.', 'source': {'pointer': '/connection_id'}, 'title': 'Invalid value for connection_id'}]`

**Comment by d-telnyx** [comment]
@msundiitalk 

instead of `call.create()` you can do something like:

```python
@csrf_exempt
def telnyx_webhook(request):
    data = json.loads(request.body).get('data')
    if data.get('record_type') == 'event':
        event = data.get('event_type')
        if event == "call.answered":
            print("say something")
            call = telnyx.Call()
            call.call_control_id = data.get('payload').get('call_control_id')
            call.speak(payload="Say this on the call")
```

That should create the empty object for you to add the `id` to instead of creating a new call.

**Comment by msundiitalk** [comment]
Thanks you @d-telnyx ,  I have new requirement:
When I make a call , I need to gather user input digital number,  

According to doc: 
1. use [Gather using speak](https://developers.telnyx.com/docs/api/v2/call-control/Call-Commands#callGatherUsingSpeak)
2. use [call.dtmf.received] to gather user input
3. use [call.gather.ended](https://developers.telnyx.com/docs/api/v2/call-control/Call-Commands#callGatherStop) to stop gather when user input #

But it seems no call.dtmf.received and call.gather.ended method in telnyx-python
When do you think they will be added or it already done?

telnyx-python/telnyx/api_resources/call.py
