### ISSUE TITLE
SIM Card Wireless Logs

### ISSUE THREAD

**Issue by sloweclair** [team-telnyx/telnyx-python#69]
Hello, I would like to get the sim card wireless logs, but the code for this is commented out with `deprecated?`. I don't think its deprecated as the v2 API has the API call

https://github.com/team-telnyx/telnyx-python/blob/c78e3a92c70423cd6c60bbcd7e3d2cd15c74c03a/telnyx/api_resources/sim_card.py#L52-L55

https://developers.telnyx.com/docs/api/v2/wireless/SIM-Cards#WirelessConnectivityLogsGet

**Comment by ADandyGuyInSpace** [comment]
Version is deprecated, this now lives under another endpoint (reporting)
