### ISSUE TITLE
Gather DTFM

### ISSUE THREAD

**Issue by PhenomAmd** [team-telnyx/telnyx-python#70]
I have been reading your documentation the whole day regarding the api ussage, first of all i find myself with something weird:

```
import telnyx
telnyx.api_key = "YOUR_API_KEY"

telnyx.Calls.post_actions.post_gather.create(client_state="aGF2ZSBhIG5pY2UgZGF5ID1d",command_id="891510ac-f3e4-11e8-af5b-de00688a4901")
```

first error here is that there is no "Calls" method inside telnyx but Call
![imagen](https://user-images.githubusercontent.com/43511497/183464402-27fc619f-9d80-4f51-b6b9-206c46b11826.png)

second theres no post actions inside Call
![imagen](https://user-images.githubusercontent.com/43511497/183464474-f9579805-9df5-48f5-9311-9bd4a1170cd0.png)

so i tried the most common thing around watching another languages to figure out how to call gather then i see ruby wich only starts a call 

![imagen](https://user-images.githubusercontent.com/43511497/183464801-982d508e-b891-4447-9b80-a664a4b80949.png)

then watched php wich also just starts a call 

```
\Telnyx\Telnyx::setApiKey('YOUR_API_KEY');

\Telnyx\Call::Create(["client_state" => "aGF2ZSBhIG5pY2UgZGF5ID1d","command_id" => "891510ac-f3e4-11e8-af5b-de00688a4901"]);
```
then saw curl wich seems to gather something nevertheless it doesnt seem to gather nothing aswell 

```
curl -X POST \
  --header "Content-Type: application/json" \
  --header "Accept: application/json" \
  --header "Authorization: Bearer YOUR_API_KEY" \
  --data '{"client_state":"aGF2ZSBhIG5pY2UgZGF5ID1d","command_id":"891510ac-f3e4-11e8-af5b-de00688a4901"}' \
  https://api.telnyx.com/v2/calls/{call_control_id}/actions/gather

```

which makes me think did you made this on purpose or is it a hard error or maybe im totally blind or maybe its just a wrong method please update your documentation or at least provide an actual working example instead of "pseudo-commands"

**Comment by ADandyGuyInSpace** [comment]
Method should now be documented on live site, apologies for the trouble and late response.
