### ISSUE TITLE
Python package cannot be run without "pip install six"

### ISSUE THREAD

**Issue by torrinworx** [team-telnyx/telnyx-python#72]
Since this package doesn't include a requirements.txt, the requirement "six" is not installed when following the installation instructions. I recommend creating a requirements.txt file to handle dependency installation so users don't have to self diagnose issues with this package's installation process and manually install the necessary dependencies to run this SDK. Pip should have also installed this dependency automatically, as is the norm with most pip packages, so my guess is there is a configuration issue with the setup file. 

I'm running Python 3.10.6 and pip 22.2.1, hope this helps!

**Comment by raiderrobert** [comment]
Ran into the same problem here.

`six` should be included in the `setup.py` file as a requirement.

**Comment by moazradwan** [comment]
Still not working after updating six any other solution?

**Comment by michaelshann0n2** [comment]
> Still not working after updating six any other solution?

I updated my version of python to python-3.9.18 and it worked.
