### ISSUE TITLE
Add Missing API Endpoints (Bounty)

### ISSUE THREAD

**Issue by ADandyGuyInSpace** [team-telnyx/telnyx-python#74]
Telnyx openapi spec file located here: https://github.com/team-telnyx/openapi/blob/master/openapi/spec3.json

We need to update this SDK to include the missing endpoints. These are the documented endpoints that are done and the ones that need to be done: https://docs.google.com/spreadsheets/d/1T45c6fvEgm9WEHHqT8OO7ZeYckOf9-oPxSknE__2rX0/edit?usp=sharing

Feel free to ask for access and will share. Should be straightforward, following same guidelines and adding tests as you go on. Use old endpoints as reference.

**Comment by vionash** [comment]
There is a bounty for this issue if you want to contribute: https://gitpay.me/#/task/713/add-missing-api-endpoints

**Comment by Hamma111** [comment]
Requested access to the document (hammad@barq.dev). You guys look cool bunch of people to work with. Won't mind working for free / lower rates for some time to develop confidence with the team!
