### ISSUE TITLE
Consider removing `black` from requirements for end users that use `pip install telnyx`.

### ISSUE THREAD

**Issue by jbwalker26** [team-telnyx/telnyx-python#88]
I noticed after installing `telnyx` via `pip` that `black` gets installed as well.  As far as I know it is just a linter, and has no practical use to the end user (which users may use some other linter or none at all for production code).

If it makes sense, could this be revised so that `black` is not included (at least for production users).  If there is actually some use cases within the main code, then I will not worry about it.

Thank you for your time.

**Comment by ADandyGuyInSpace** [comment]
You're absolutely right, this was moved into the repo accidentally should only be available in the development install. Pushing in 2.1.4
